Feature/155 story state machine
GenoImel/The-Mechanical-Forest pull request #187
Opened 2023-11-03 19:40 UTC by jckrebs

Closes #155. Closes #154. Closes #153.

This PR adds a StoryStateMachine and uses it to refactor the way we were checking to see when story events were active.

There are two bugs that seem to no longer exist now (#154, #153). While you can click and drag the scroll view in the dialogue history window, it doesn't actually let you continuously scroll through blank space. Also, continuously clicking and scrolling through the dialogue history window doesn't seem to produce duplicate line entries anymore.

**Testing**

Load up the test scene located at `Assets/Scenes/Test/StoryMonoSystem_Test/StoryMonoSystemScene_Test.unity` and click the red square to experience a story event. Try clicking through the dialogue and playing around with the dialogue history (by clicking the log button in the top right corner) to see if you can recreate the bugs from #153 or #154.

2023-11-03 19:45 UTC, yokozach submitted a review, later dismissed

2023-11-04 13:33 UTC, GenoImel commented on Assets/Scripts/Runtime/StateMachines/StoryStates/IStoryStateMachine.cs
> +        public IFiniteState CurrentState { get; }
Might be good to move this guy to the top, and add some XML documentation.

2023-11-04 13:34 UTC, GenoImel commented on Assets/Scripts/Runtime/StateMachines/StoryStates/StoryStateMachine.cs
> +        }
Missed a line break.

2023-11-04 13:35 UTC, GenoImel commented on Documentation~/CoreArchitecture.md
> +`Message Events` are essential for communicating `state` changes within our individual `StateMachines`. The `StateChangedMessage` serves as a specialized `Message Event` for any `state` changes, and
Nice catch... also reminds me that I need to do another PR to update the documentation, since we now have the autoproperty for getting the `currentState`. 😅

2023-11-04 13:36 UTC, GenoImel commented on Assets/Scripts/Runtime/Controllers/Story/StoryController.cs
> +            storyState = GameManager.GetStateMachine<IStoryStateMachine>();
Might be good to name this variable `storyStateMachine`, just so it's clear that this is a `State Machine` and not an `IFiniteState` when its used in the code later. 🤔

2023-11-04 13:38 UTC, GenoImel commented on Assets/Scripts/Runtime/MonoSystems/Story/StoryEventInjector.cs
> +            if (storyState.CurrentState is StoryFiniteState.Active)
Originally I was thinking this would happen in the `StoryMonoSystem`... but I honestly like this better. Prevents the `StoryEventInjector` from publishing the `NewStoryEventMessage` at all, which results in much less `Message Bus` pollution. 😄

2023-11-04 13:39 UTC, GenoImel requested changes
This looks really good, great job on this. I only have some small, nit-picky changes that I requested, mostly for coding standards adherence.

It's really nice to see some of those bugs disappear, and how much cleaner the code got with the new `State Machine`. 😄

2023-12-24 02:13 UTC, GenoImel approved these changes

2023-12-24 02:19 UTC, merged